# GENERATED by scripts/services.mjs (S9 · OWNERSHIP, 28 Aug 2026) — do not hand-edit.
#
# dugout IS A LOGON TASK AND NOT A SERVICE, ON PURPOSE:
#   HIS voice surface — it needs a microphone and a browser, which session 0 has neither of
# Installing it as a service would SUCCEED and then do nothing, which is worse than
# failing — session-0 isolation is silent.
#
# This registers the task. It does NOT start it: S9 installs ownership, S12 turns
# things on, HIS word per stage.

$ErrorActionPreference = "Stop"
$repo = "C:\Users\nikhi\GitHub\arsenal-ai-fc"
$id   = "ArsenalFC-Dugout"

$action    = New-ScheduledTaskAction -Execute "wscript.exe" `
             -Argument ("`"$repo\setup\hidden_run.vbs`" node scripts\dugout.mjs") `
             -WorkingDirectory $repo
$trigger   = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

# THE TWO SETTINGS THE AUDIT ASKED FOR, by name:
#   StartWhenAvailable — a laptop that was asleep at the trigger runs the task when
#                        it wakes, instead of silently skipping the day.
#   RestartOnFailure   — the supervision that used to live in the watchdog's arm.
# Battery kill-conditions are cleared here for the same reason every other installer
# in setup/ clears them (the 12-Jul scar: the whole organism queued itself off).
$settings = New-ScheduledTaskSettingsSet `
             -StartWhenAvailable `
             -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
             -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
             -ExecutionTimeLimit (New-TimeSpan -Hours 0)

Register-ScheduledTask -TaskName $id -Action $action -Trigger $trigger `
  -Principal $principal -Settings $settings -Force | Out-Null

# ⛔ REGISTERED AND IMMEDIATELY DISABLED — this is not a mistake.
# The organism is SWITCHED OFF by his order of 20 Aug 2026. S9 installs ownership;
# S12 enables, stage by stage, on his word. Enabling here would break the switch-off.
Disable-ScheduledTask -TaskName $id | Out-Null

Write-Host "  ~ $id registered as a LOGON TASK (disabled — S12 enables it on his word)"
