# ============================================================================
# grant-logon-right.ps1 — GENERATED by scripts/services.mjs (S9 · OWNERSHIP)
#
# Grants "Log on as a service" (SeServiceLogonRight) to the account the daemons run as.
# Run ELEVATED:
#     powershell -ExecutionPolicy Bypass -File "C:\Users\nikhi\GitHub\arsenal-ai-fc\setup\services\grant-logon-right.ps1"
#
# WHY IT IS NEEDED: sc.exe sets a service's logon account but does NOT grant this right,
# and WinSW's own <allowservicelogonright> never applied here because the credential
# deliberately goes through sc.exe and never touches a file. Without the right, every
# service installs cleanly and then FAILS TO START — surfacing much later as a confusing
# "logon failure" nowhere near its cause.
#
# It asks for NO password and installs NOTHING. Safe to run again.
# ============================================================================
$ErrorActionPreference = "Stop"
$account = if ($args.Count -ge 1) { $args[0] } else { "$env:USERNAME" }

try { $sid = (New-Object System.Security.Principal.NTAccount($account)).Translate([System.Security.Principal.SecurityIdentifier]).Value }
catch { Write-Host "  cannot resolve account '$account': $($_.Exception.Message)"; exit 1 }

Write-Host "  account : $account"
Write-Host "  sid     : $sid"

# ── THE WRITE GOES THROUGH THE LSA API, NOT THROUGH secedit ───────────────────
# The first version edited the exported .inf and fed it back with
# `secedit /configure`. It ran without complaint and changed NOTHING — the read-back
# proved the right still absent, which is the only reason we know. secedit's INF
# round-trip is fragile (it silently drops a section it does not fully parse) and this
# is Windows 11 HOME, where there is no secpol.msc to fall back to either.
#
# LsaAddAccountRights is the API the policy editor itself calls. It works on Home, it
# is idempotent, and it returns a real error code instead of a shrug.
$sig = @'
using System;
using System.Runtime.InteropServices;
public static class ArsenalLsa {
  [StructLayout(LayoutKind.Sequential)]
  struct LSA_UNICODE_STRING { public ushort Length; public ushort MaximumLength; public IntPtr Buffer; }
  [StructLayout(LayoutKind.Sequential)]
  struct LSA_OBJECT_ATTRIBUTES { public int Length; public IntPtr RootDirectory; public IntPtr ObjectName; public int Attributes; public IntPtr SecurityDescriptor; public IntPtr SecurityQualityOfService; }
  [DllImport("advapi32.dll", SetLastError=true)]
  static extern uint LsaOpenPolicy(IntPtr SystemName, ref LSA_OBJECT_ATTRIBUTES oa, int access, out IntPtr handle);
  [DllImport("advapi32.dll", SetLastError=true)]
  static extern uint LsaAddAccountRights(IntPtr policy, byte[] sid, LSA_UNICODE_STRING[] rights, int count);
  [DllImport("advapi32.dll", SetLastError=true)]
  static extern uint LsaEnumerateAccountRights(IntPtr policy, byte[] sid, out IntPtr rights, out uint count);
  [DllImport("advapi32.dll")] static extern uint LsaFreeMemory(IntPtr p);
  [DllImport("advapi32.dll")] static extern uint LsaClose(IntPtr h);
  [DllImport("advapi32.dll")] static extern int LsaNtStatusToWinError(uint status);
  public static int Grant(byte[] sid, string right) {
    var oa = new LSA_OBJECT_ATTRIBUTES(); oa.Length = Marshal.SizeOf(oa);
    IntPtr h;
    uint st = LsaOpenPolicy(IntPtr.Zero, ref oa, 0x10 | 0x20 | 0x00000800, out h);
    if (st != 0) return LsaNtStatusToWinError(st);
    var r = new LSA_UNICODE_STRING[1];
    r[0].Buffer = Marshal.StringToHGlobalUni(right);
    r[0].Length = (ushort)(right.Length * 2);
    r[0].MaximumLength = (ushort)((right.Length + 1) * 2);
    st = LsaAddAccountRights(h, sid, r, 1);
    LsaClose(h);
    Marshal.FreeHGlobal(r[0].Buffer);
    return LsaNtStatusToWinError(st);
  }
  // THE READ, through the SAME API as the write. secedit's export was the first
  // verifier and it disagreed with a write that had returned SUCCESS — so it was
  // measuring something other than live LSA. Two mechanisms that disagree is one
  // mechanism too many; this reads back from where the write landed.
  public static string[] Rights(byte[] sid, out int err) {
    err = 0; var oa = new LSA_OBJECT_ATTRIBUTES(); oa.Length = Marshal.SizeOf(oa); IntPtr h;
    uint st = LsaOpenPolicy(IntPtr.Zero, ref oa, 0x20 | 0x00000800, out h);
    if (st != 0) { err = LsaNtStatusToWinError(st); return new string[0]; }
    IntPtr buf; uint cnt;
    st = LsaEnumerateAccountRights(h, sid, out buf, out cnt);
    if (st != 0) { err = LsaNtStatusToWinError(st); LsaClose(h); return new string[0]; }
    var list = new System.Collections.Generic.List<string>();
    int sz = Marshal.SizeOf(typeof(LSA_UNICODE_STRING));
    for (int i = 0; i < cnt; i++) {
      var u = (LSA_UNICODE_STRING)Marshal.PtrToStructure(new IntPtr(buf.ToInt64() + i * sz), typeof(LSA_UNICODE_STRING));
      list.Add(Marshal.PtrToStringUni(u.Buffer, u.Length / 2));
    }
    LsaFreeMemory(buf); LsaClose(h);
    return list.ToArray();
  }
}
'@
try { Add-Type -TypeDefinition $sig -ErrorAction Stop } catch { }
$sidObj = New-Object System.Security.Principal.SecurityIdentifier($sid)
$bytes  = New-Object byte[] ($sidObj.BinaryLength)
$sidObj.GetBinaryForm($bytes, 0)

# READ FIRST — through the same API the write uses. Error 5 here means this window is
# not elevated (the read needs rights too), and that is reported as UNKNOWN, never as
# "not granted": a permission failure is not a measurement.
$e = 0
$before = [ArsenalLsa]::Rights($bytes, [ref]$e)
if ($e -eq 5) {
  Write-Host "  RESULT  : CANNOT READ — this window is not ELEVATED (access denied)."
  Write-Host "            Re-run from an Administrator PowerShell. Nothing was changed."
  exit 1
}
if ($e -ne 0) { Write-Host "  note    : reading rights returned Win32 error $e" }
Write-Host "  before  : $(if ($before.Count) { $before -join ', ' } else { '(none)' })"

if ($before -contains "SeServiceLogonRight") {
  Write-Host "  RESULT  : ALREADY GRANTED — nothing to do."
  exit 0
}

$rc = [ArsenalLsa]::Grant($bytes, "SeServiceLogonRight")
# PRINTED ALWAYS, not only on failure. The previous build printed this only when it was
# non-zero, so a SUCCESSFUL grant that a broken verifier then called a failure looked
# like silence — and silence is where a wrong diagnosis hides.
Write-Host "  grant rc: $rc$(if ($rc -eq 0) { ' (success)' } else { ' (Win32 error)' })"

# READ IT BACK. A claim is read off the outcome, never off the call — the law this
# whole rung exists to enforce, and the one I broke three times building it.
$e2 = 0
$after = [ArsenalLsa]::Rights($bytes, [ref]$e2)
Write-Host "  after   : $(if ($after.Count) { $after -join ', ' } else { '(none)' })"

if ($after -contains "SeServiceLogonRight") {
  Write-Host "  RESULT  : GRANTED — read back from live LSA, not inferred from the call."
  exit 0
}
Write-Host "  RESULT  : FAILED — the grant returned $rc and the right is still absent."
Write-Host "            (secpol.msc does NOT exist on Windows Home, so that is not the fallback.)"
Write-Host "            Report the whole block above; S12 must not turn anything on until this reads GRANTED."
exit 1
