# ============================================================================
# grant-logon-right.ps1 — GENERATED by scripts/services.mjs (S9 · OWNERSHIP)
#
# Grants "Log on as a service" (SeServiceLogonRight) to the account the daemons run as.
# Run ELEVATED:
#     powershell -ExecutionPolicy Bypass -File setup\services\grant-logon-right.ps1
#
# WHY IT IS NEEDED: sc.exe sets a service's logon account but does NOT grant this right,
# and WinSW's own <allowservicelogonright> never applied here because the credential
# deliberately goes through sc.exe and never touches a file. Without the right, every
# service installs cleanly and then FAILS TO START — surfacing much later as a confusing
# "logon failure" nowhere near its cause.
#
# It asks for NO password and installs NOTHING. Safe to run again.
# ============================================================================
$ErrorActionPreference = "Stop"
$account = if ($args.Count -ge 1) { $args[0] } else { "$env:USERNAME" }

try { $sid = (New-Object System.Security.Principal.NTAccount($account)).Translate([System.Security.Principal.SecurityIdentifier]).Value }
catch { Write-Host "  cannot resolve account '$account': $($_.Exception.Message)"; exit 1 }

$inf = Join-Path $env:TEMP "arsenal_right.inf"
$db  = Join-Path $env:TEMP "arsenal_right.sdb"
Remove-Item $inf, $db -Force -ErrorAction SilentlyContinue

$export = secedit /export /cfg $inf /areas USER_RIGHTS 2>&1
if (-not (Test-Path $inf)) {
  Write-Host "  COULD NOT READ the policy — this needs an ELEVATED PowerShell."
  Write-Host "  $export"
  exit 1
}

$txt  = Get-Content $inf
$line = $txt | Where-Object { $_ -match '^SeServiceLogonRight' }
Write-Host "  account : $account"
Write-Host "  sid     : $sid"

if ($line -and $line -match [regex]::Escape($sid)) {
  Write-Host "  RESULT  : ALREADY GRANTED — nothing to do."
  Remove-Item $inf, $db -Force -ErrorAction SilentlyContinue
  exit 0
}

$new = if ($line) { "$line,*$sid" } else { "SeServiceLogonRight = *$sid" }
$out = if ($line) { $txt -replace [regex]::Escape($line), $new }
       else       { $txt -replace '^\[Privilege Rights\]', "[Privilege Rights]`r`n$new" }
Set-Content -Path $inf -Value $out -Encoding Unicode
secedit /configure /db $db /cfg $inf /areas USER_RIGHTS | Out-Null

# READ IT BACK. A claim is read off the outcome, never off the call — the law this
# whole rung exists to enforce, and the one I broke three times building it.
Remove-Item $inf -Force -ErrorAction SilentlyContinue
secedit /export /cfg $inf /areas USER_RIGHTS | Out-Null
$after = (Get-Content $inf | Where-Object { $_ -match '^SeServiceLogonRight' })
Remove-Item $inf, $db -Force -ErrorAction SilentlyContinue

if ($after -and $after -match [regex]::Escape($sid)) {
  Write-Host "  RESULT  : GRANTED, and read back from the policy to prove it."
  exit 0
}
Write-Host "  RESULT  : FAILED — the right is still not present after the change."
Write-Host "            Do it by hand: secpol.msc -> Local Policies -> User Rights Assignment"
Write-Host "            -> Log on as a service -> add $account"
exit 1
