# ============================================================================
# grant-service-control.ps1 — GENERATED by scripts/services.mjs. Do not hand-edit.
#
# Lets .\arsenal-svc restart ITS OWN services when a child dies — the arm the
# S9 XMLs already ask for and the SCM has been refusing. Run ELEVATED.
#
# Least privilege: start/stop/query only. It may NOT delete a service and may NOT
# change a service's permissions or owner.
# Idempotent: an account already present is skipped, not doubled.
# Revert: the pre-change descriptor of every service is written to a backup file
#         whose full path is printed at the end. sc.exe sdset <name> <old> undoes it.
# ============================================================================
$ErrorActionPreference = "Stop"
$account = ".\arsenal-svc"
$services = @("ArsenalFC-Cortex", "ArsenalFC-Thalamus", "ArsenalFC-Brain", "ArsenalFC-Sitting", "ArsenalFC-Context")

try { $sid = (New-Object System.Security.Principal.NTAccount("arsenal-svc")).Translate([System.Security.Principal.SecurityIdentifier]).Value }
catch { Write-Host "  X cannot resolve arsenal-svc - create the account first. Nothing changed."; exit 1 }

# START + STOP + the three reads WinSW needs to know what it is restarting.
# No DC/SD (delete), no WD/WO (rewrite permissions) - see the generator's comment.
$ace = "(A;;CCLCSWRPWPLORC;;;" + $sid + ")"
$backup = Join-Path $env:USERPROFILE ("arsenal-service-sddl-backup.txt")

Write-Host ""
Write-Host "  Granting SELF-RESTART to $account on its own $($services.Count) service(s)"
Write-Host "  sid : $sid"
Write-Host ""

$bad = 0
$lines = @("# Arsenal AI FC - service descriptors BEFORE grant-service-control.ps1", "# revert one row with:  sc.exe sdset <name> <descriptor>")
foreach ($s in $services) {
  # READ THE LIVE ONE. Never assume the five are identical, even when they were emitted
  # together - a hand fix on one service would be silently overwritten by a stored copy.
  $old = ((sc.exe sdshow $s) -join "").Trim()
  if ($LASTEXITCODE -ne 0 -or -not $old.StartsWith("D:")) {
    Write-Host "  X $s - could not read its descriptor; skipped, nothing changed"
    $bad++; continue
  }
  $lines += ($s + " " + $old)
  if ($old -like ("*" + $sid + "*")) { Write-Host "  = $s already granted - skipped"; continue }

  # APPEND to the DACL, never rewrite it. An S: (audit) section, if present, must stay
  # AFTER the DACL, so the ace goes at the END OF D: and not at the end of the string.
  # (The first version wrote [^S]* here, which cannot work: SY, SW, SD and SU all contain
  # an S, so it could never reach a literal "S:". It fell through to the else every time
  # and was right by accident. Split on the marker, not on "anything but its first letter".)
  $sacl = ""
  $dacl = $old
  $cut  = $old.IndexOf("S:")
  if ($cut -gt 0) { $dacl = $old.Substring(0, $cut); $sacl = $old.Substring($cut) }

  # ⚠ TWO FORMS, TRIED IN ORDER, BECAUSE THE FIRST ONE WAS MEASURED TO FAIL — 30 Aug 2026.
  # sc.exe accepted the service and then answered "The specified datatype is invalid" on all
  # five, while .NET's own RawSecurityDescriptor parsed the SAME string cleanly and round-
  # tripped it byte-identical. So the descriptor is valid and sc.exe wants a different SHAPE
  # of it. The documented difference is that sdset can demand a SACL section even where
  # sdshow returned none. Rather than guess which, this TRIES and REPORTS which one worked —
  # and whichever it is becomes a measured fact instead of a belief.
  $forms = @(
    @{ name = "D: only";        sd = ($dacl + $ace + $sacl) },
    @{ name = "D: + empty S:";  sd = ($dacl + $ace + $(if ($sacl) { $sacl } else { "S:" })) }
  )
  $done = $false
  foreach ($f in $forms) {
    $out = & sc.exe sdset $s $f.sd 2>&1
    if ($LASTEXITCODE -eq 0) { Write-Host "  . $s accepted the [$($f.name)] form"; $done = $true; break }
    Write-Host "  . $s refused the [$($f.name)] form: $(($out | Where-Object { $_ -match 'S' } | Select-Object -Last 1))"
  }
  if (-not $done) {
    Write-Host "  X $s FAILED - every form refused. Nothing changed for this service."
    $bad++; continue
  }
  # THE CLAIM IS READ OFF THE OUTCOME, never off the call - sdset has printed SUCCESS on
  # descriptors it did not fully apply. Ask the SCM what it holds now.
  $back = ((sc.exe sdshow $s) -join "").Trim()
  if ($back -like ("*" + $sid + "*")) { Write-Host "  ~ $s granted, verified by read-back" }
  else { Write-Host "  X $s - sdset returned success but the read-back does NOT carry the account"; $bad++ }
}

Set-Content -Path $backup -Value $lines -Encoding utf8
Write-Host ""
Write-Host "  revert file: $backup"
if ($bad -gt 0) { Write-Host "  INCOMPLETE - $bad service(s) failed. Safe to re-run."; exit 1 }
Write-Host "  DONE. Nothing was started or stopped."
Write-Host "  PROVE IT: kill a daemon's node child and it must come back on its own within ~15s."
