# ============================================================================
# install.ps1 — GENERATED by scripts/services.mjs (S9 · OWNERSHIP, 28 Aug 2026)
#
# THIS IS THE ONE THING THAT NEEDS HIS HANDS. Everything else in S9 is on disk.
# Run it from an ELEVATED PowerShell (services need admin to register):
#     powershell -ExecutionPolicy Bypass -File setup\services\install.ps1
#
# IT WILL ASK FOR HIS WINDOWS PASSWORD, ONCE. That is not avoidable and it is not
# a smell: the headless daemons must run AS HIM (they read his state, his tokens,
# his study), and Windows will not let a service log on as a user without the
# user's own credential. The password goes from his keyboard into the Service
# Control Manager. It is never written to a file, never echoed, and no Claude
# session ever sees it — that is a standing law, not a courtesy.
#
# ⛔ NOTHING IS STARTED. Every service is installed with start=demand and every
# task is registered disabled. S12 turns things on, stage by stage, on his word.
# ============================================================================
$ErrorActionPreference = "Stop"
$repo = "C:\Users\nikhi\GitHub\arsenal-ai-fc"
$here = Join-Path $repo "setup\services"

# WinSW is a single .exe. It is NOT vendored into the repo — it is a binary, and a
# binary in a git repo is a supply-chain question nobody asked. Point this at the
# copy he downloads, or set ARSENAL_WINSW.
# ANY WinSW*.exe IN THIS FOLDER WILL DO, and that is deliberate. Windows hides known
# extensions in Explorer, so renaming the downloaded "WinSW-x64.exe" to "WinSW.exe"
# produces "WinSW.exe.exe" on disk - which is exactly what happened here on the first
# try. Demanding one exact filename would have stopped him with a "not found" for a
# file he could plainly see. Pattern-matched instead, newest first.
$winsw = $env:ARSENAL_WINSW
if (-not $winsw) {
  $found = Get-ChildItem -Path $here -Filter "WinSW*.exe" -File -ErrorAction SilentlyContinue |
           Sort-Object LastWriteTime -Descending | Select-Object -First 1
  if ($found) { $winsw = $found.FullName }
}
if (-not $winsw -or -not (Test-Path $winsw)) {
  Write-Host ""
  Write-Host "  No WinSW*.exe found in: $here"
  Write-Host "  Download the x64 release from https://github.com/winsw/winsw/releases,"
  Write-Host "  drop it in setup\services\ under any WinSW* name, and re-run."
  Write-Host "  (Or set ARSENAL_WINSW to its full path.)"
  Write-Host "  Nothing has been changed."
  exit 1
}
Write-Host "  using WinSW: $winsw"

Write-Host ""
Write-Host "  Arsenal AI FC - OWNERSHIP INSTALL (S9)"
Write-Host "  5 headless daemon(s) as services, 2 desktop surface(s) as logon tasks."
Write-Host "  Windows will ask for your password once, for the services only."
Write-Host ""

$cred = Get-Credential -UserName "$env:USERDOMAIN\$env:USERNAME" `
        -Message "Arsenal AI FC: the account the daemons run as. This goes straight to Windows - it is not stored anywhere."

# ⚠ THE PASSWORD IS PULLED OUT INTO A VARIABLE ON PURPOSE, and this is a real bug fix,
# not a style choice. Written first as `--password $cred.GetNetworkCredential().Password`
# INLINE in the native call. PowerShell parses native-command arguments in ARGUMENT
# MODE, where a method-call chain like .GetNetworkCredential().Password is NOT reliably
# evaluated — it can reach WinSW as literal text. The service would then install with a
# junk password and fail to start with a logon error that points at his account instead
# of at this line. Caught by re-reading the generated file before he ran it elevated.
$plainPw = $cred.GetNetworkCredential().Password

# --- cortex ---
& $winsw install (Join-Path $here "ArsenalFC-Cortex.xml") --username $cred.UserName --password $plainPw
& $winsw stop    (Join-Path $here "ArsenalFC-Cortex.xml")  2>$null   # belt: install must never leave it running
sc.exe config "ArsenalFC-Cortex" start= demand | Out-Null            # S12 flips these to auto, on his word
Write-Host "  ~ ArsenalFC-Cortex installed as a SERVICE (start=demand, not running)"
# --- thalamus ---
& $winsw install (Join-Path $here "ArsenalFC-Thalamus.xml") --username $cred.UserName --password $plainPw
& $winsw stop    (Join-Path $here "ArsenalFC-Thalamus.xml")  2>$null   # belt: install must never leave it running
sc.exe config "ArsenalFC-Thalamus" start= demand | Out-Null            # S12 flips these to auto, on his word
Write-Host "  ~ ArsenalFC-Thalamus installed as a SERVICE (start=demand, not running)"
# --- brain ---
& $winsw install (Join-Path $here "ArsenalFC-Brain.xml") --username $cred.UserName --password $plainPw
& $winsw stop    (Join-Path $here "ArsenalFC-Brain.xml")  2>$null   # belt: install must never leave it running
sc.exe config "ArsenalFC-Brain" start= demand | Out-Null            # S12 flips these to auto, on his word
Write-Host "  ~ ArsenalFC-Brain installed as a SERVICE (start=demand, not running)"
# --- sitting ---
& $winsw install (Join-Path $here "ArsenalFC-Sitting.xml") --username $cred.UserName --password $plainPw
& $winsw stop    (Join-Path $here "ArsenalFC-Sitting.xml")  2>$null   # belt: install must never leave it running
sc.exe config "ArsenalFC-Sitting" start= demand | Out-Null            # S12 flips these to auto, on his word
Write-Host "  ~ ArsenalFC-Sitting installed as a SERVICE (start=demand, not running)"
# --- context ---
& $winsw install (Join-Path $here "ArsenalFC-Context.xml") --username $cred.UserName --password $plainPw
& $winsw stop    (Join-Path $here "ArsenalFC-Context.xml")  2>$null   # belt: install must never leave it running
sc.exe config "ArsenalFC-Context" start= demand | Out-Null            # S12 flips these to auto, on his word
Write-Host "  ~ ArsenalFC-Context installed as a SERVICE (start=demand, not running)"

& powershell -ExecutionPolicy Bypass -File (Join-Path $here "ArsenalFC-Turnstile.logon.ps1")
& powershell -ExecutionPolicy Bypass -File (Join-Path $here "ArsenalFC-Dugout.logon.ps1")

Remove-Variable cred, plainPw -ErrorAction SilentlyContinue   # neither outlives this script

Write-Host ""
Write-Host "  DONE - and NOTHING IS RUNNING. Verify:  node scripts/services.mjs status"
Write-Host "  S12 is what turns the organism back on, stage by stage, on your word."
