# ============================================================================
# install.ps1 — GENERATED by scripts/services.mjs (S9 · OWNERSHIP, 28 Aug 2026)
#
# THIS IS THE ONE THING THAT NEEDS HIS HANDS. Everything else in S9 is on disk.
# Run it from an ELEVATED PowerShell (services need admin to register):
#     powershell -ExecutionPolicy Bypass -File setup\services\install.ps1
#
# IT WILL ASK FOR HIS WINDOWS PASSWORD, ONCE. That is not avoidable and it is not
# a smell: the headless daemons must run AS HIM (they read his state, his tokens,
# his study), and Windows will not let a service log on as a user without the
# user's own credential. The password goes from his keyboard into the Service
# Control Manager. It is never written to a file, never echoed, and no Claude
# session ever sees it — that is a standing law, not a courtesy.
#
# ⛔ NOTHING IS STARTED. Every service is installed with start=demand and every
# task is registered disabled. S12 turns things on, stage by stage, on his word.
# ============================================================================
$ErrorActionPreference = "Stop"
$repo = "C:\Users\nikhi\GitHub\arsenal-ai-fc"
$here = Join-Path $repo "setup\services"

# WinSW is a single .exe. It is NOT vendored into the repo — it is a binary, and a
# binary in a git repo is a supply-chain question nobody asked. Point this at the
# copy he downloads, or set ARSENAL_WINSW.
# ANY WinSW*.exe IN THIS FOLDER WILL DO, and that is deliberate. Windows hides known
# extensions in Explorer, so renaming the downloaded "WinSW-x64.exe" to "WinSW.exe"
# produces "WinSW.exe.exe" on disk - which is exactly what happened here on the first
# try. Demanding one exact filename would have stopped him with a "not found" for a
# file he could plainly see. Pattern-matched instead, newest first.
$winsw = $env:ARSENAL_WINSW
if (-not $winsw) {
  $found = Get-ChildItem -Path $here -Filter "WinSW*.exe" -File -ErrorAction SilentlyContinue |
           Sort-Object LastWriteTime -Descending | Select-Object -First 1
  if ($found) { $winsw = $found.FullName }
}
if (-not $winsw -or -not (Test-Path $winsw)) {
  Write-Host ""
  Write-Host "  No WinSW*.exe found in: $here"
  Write-Host "  Download the x64 release from https://github.com/winsw/winsw/releases,"
  Write-Host "  drop it in setup\services\ under any WinSW* name, and re-run."
  Write-Host "  (Or set ARSENAL_WINSW to its full path.)"
  Write-Host "  Nothing has been changed."
  exit 1
}
Write-Host "  using WinSW: $winsw"

Write-Host ""
Write-Host "  Arsenal AI FC - OWNERSHIP INSTALL (S9)"
Write-Host "  5 headless daemon(s) as services, 2 desktop surface(s) as logon tasks."
Write-Host "  Windows will ask for your password once, for the services only."
Write-Host ""

$cred = Get-Credential -UserName "$env:USERDOMAIN\$env:USERNAME" `
        -Message "Arsenal AI FC: the account the daemons run as. This goes straight to Windows - it is not stored anywhere."

# ⚠ THE PASSWORD IS PULLED OUT INTO A VARIABLE ON PURPOSE, and this is a real bug fix,
# not a style choice. Written first as `--password $cred.GetNetworkCredential().Password`
# INLINE in the native call. PowerShell parses native-command arguments in ARGUMENT
# MODE, where a method-call chain like .GetNetworkCredential().Password is NOT reliably
# evaluated — it can reach WinSW as literal text. The service would then install with a
# junk password and fail to start with a logon error that points at his account instead
# of at this line. Caught by re-reading the generated file before he ran it elevated.
$plainPw = $cred.GetNetworkCredential().Password

# ── HOW WinSW v2 ACTUALLY WORKS, learned by running it and being wrong first ──
# WinSW v2 (the current STABLE line, and what he downloaded) finds its config by its
# OWN EXECUTABLE NAME: <exe-basename>.xml sitting beside it. It does NOT accept a
# config path as an argument - that is the v3 form, and assuming it produced this on
# every one of five services:
#   FATAL - System.IO.FileNotFoundException: Unable to locate WinSW.exe.[xml|yml]
#           file within executable directory
# So the exe is COPIED ONCE PER SERVICE to <ServiceId>.exe, beside the <ServiceId>.xml
# that is already generated here. That is the documented v2 pattern, not a workaround.
# The copies are gitignored; they cost disk, and disk is the cheap resource here.
$failed = @()

# --- cortex ---
$id  = "ArsenalFC-Cortex"
$exe = Join-Path $here "$id.exe"
Copy-Item -LiteralPath $winsw -Destination $exe -Force
# v2 takes NO config argument - it reads "$id.xml" because the exe is named "$id.exe".
& $exe install 2>&1 | ForEach-Object { if ($_ -match "FATAL|Exception") { Write-Host "      winsw: $_" } }
# THE CLAIM IS READ OFF THE OUTCOME, NEVER OFF THE CALL. The previous build printed
# "installed as a SERVICE" unconditionally and said it five times while installing
# NOTHING - the exact defect this whole rung exists to remove, committed inside the
# organ that removes it. Ask the SCM instead.
$svc = Get-Service -Name $id -ErrorAction SilentlyContinue
if (-not $svc) {
  Write-Host "  X $id FAILED to install - see the winsw line(s) above"
  $failed += $id
} else {
  # The account is set through sc.exe, NOT through the XML: WinSW would take a
  # <password> element, and a password persisted in a repo file is the one thing
  # this generator refuses to do.
  sc.exe config $id obj= $cred.UserName password= $plainPw | Out-Null
  sc.exe config $id start= demand | Out-Null   # S12 flips these to auto, on his word
  $acct = (Get-CimInstance Win32_Service -Filter "Name='$id'").StartName
  if ($acct -and ($acct -replace '^\.\\', "$env:COMPUTERNAME\\") -ieq ($cred.UserName -replace '^\.\\', "$env:COMPUTERNAME\\")) {
    Write-Host "  ~ $id installed, runs as $acct, start=demand, NOT running"
  } else {
    Write-Host "  ! $id installed but its logon account reads '$acct', not '$($cred.UserName)'"
    Write-Host "      fix once in services.msc -> $id -> Log On tab, or it will fail to start at S12"
    $failed += "$id (account)"
  }
}

# --- thalamus ---
$id  = "ArsenalFC-Thalamus"
$exe = Join-Path $here "$id.exe"
Copy-Item -LiteralPath $winsw -Destination $exe -Force
# v2 takes NO config argument - it reads "$id.xml" because the exe is named "$id.exe".
& $exe install 2>&1 | ForEach-Object { if ($_ -match "FATAL|Exception") { Write-Host "      winsw: $_" } }
# THE CLAIM IS READ OFF THE OUTCOME, NEVER OFF THE CALL. The previous build printed
# "installed as a SERVICE" unconditionally and said it five times while installing
# NOTHING - the exact defect this whole rung exists to remove, committed inside the
# organ that removes it. Ask the SCM instead.
$svc = Get-Service -Name $id -ErrorAction SilentlyContinue
if (-not $svc) {
  Write-Host "  X $id FAILED to install - see the winsw line(s) above"
  $failed += $id
} else {
  # The account is set through sc.exe, NOT through the XML: WinSW would take a
  # <password> element, and a password persisted in a repo file is the one thing
  # this generator refuses to do.
  sc.exe config $id obj= $cred.UserName password= $plainPw | Out-Null
  sc.exe config $id start= demand | Out-Null   # S12 flips these to auto, on his word
  $acct = (Get-CimInstance Win32_Service -Filter "Name='$id'").StartName
  if ($acct -and ($acct -replace '^\.\\', "$env:COMPUTERNAME\\") -ieq ($cred.UserName -replace '^\.\\', "$env:COMPUTERNAME\\")) {
    Write-Host "  ~ $id installed, runs as $acct, start=demand, NOT running"
  } else {
    Write-Host "  ! $id installed but its logon account reads '$acct', not '$($cred.UserName)'"
    Write-Host "      fix once in services.msc -> $id -> Log On tab, or it will fail to start at S12"
    $failed += "$id (account)"
  }
}

# --- brain ---
$id  = "ArsenalFC-Brain"
$exe = Join-Path $here "$id.exe"
Copy-Item -LiteralPath $winsw -Destination $exe -Force
# v2 takes NO config argument - it reads "$id.xml" because the exe is named "$id.exe".
& $exe install 2>&1 | ForEach-Object { if ($_ -match "FATAL|Exception") { Write-Host "      winsw: $_" } }
# THE CLAIM IS READ OFF THE OUTCOME, NEVER OFF THE CALL. The previous build printed
# "installed as a SERVICE" unconditionally and said it five times while installing
# NOTHING - the exact defect this whole rung exists to remove, committed inside the
# organ that removes it. Ask the SCM instead.
$svc = Get-Service -Name $id -ErrorAction SilentlyContinue
if (-not $svc) {
  Write-Host "  X $id FAILED to install - see the winsw line(s) above"
  $failed += $id
} else {
  # The account is set through sc.exe, NOT through the XML: WinSW would take a
  # <password> element, and a password persisted in a repo file is the one thing
  # this generator refuses to do.
  sc.exe config $id obj= $cred.UserName password= $plainPw | Out-Null
  sc.exe config $id start= demand | Out-Null   # S12 flips these to auto, on his word
  $acct = (Get-CimInstance Win32_Service -Filter "Name='$id'").StartName
  if ($acct -and ($acct -replace '^\.\\', "$env:COMPUTERNAME\\") -ieq ($cred.UserName -replace '^\.\\', "$env:COMPUTERNAME\\")) {
    Write-Host "  ~ $id installed, runs as $acct, start=demand, NOT running"
  } else {
    Write-Host "  ! $id installed but its logon account reads '$acct', not '$($cred.UserName)'"
    Write-Host "      fix once in services.msc -> $id -> Log On tab, or it will fail to start at S12"
    $failed += "$id (account)"
  }
}

# --- sitting ---
$id  = "ArsenalFC-Sitting"
$exe = Join-Path $here "$id.exe"
Copy-Item -LiteralPath $winsw -Destination $exe -Force
# v2 takes NO config argument - it reads "$id.xml" because the exe is named "$id.exe".
& $exe install 2>&1 | ForEach-Object { if ($_ -match "FATAL|Exception") { Write-Host "      winsw: $_" } }
# THE CLAIM IS READ OFF THE OUTCOME, NEVER OFF THE CALL. The previous build printed
# "installed as a SERVICE" unconditionally and said it five times while installing
# NOTHING - the exact defect this whole rung exists to remove, committed inside the
# organ that removes it. Ask the SCM instead.
$svc = Get-Service -Name $id -ErrorAction SilentlyContinue
if (-not $svc) {
  Write-Host "  X $id FAILED to install - see the winsw line(s) above"
  $failed += $id
} else {
  # The account is set through sc.exe, NOT through the XML: WinSW would take a
  # <password> element, and a password persisted in a repo file is the one thing
  # this generator refuses to do.
  sc.exe config $id obj= $cred.UserName password= $plainPw | Out-Null
  sc.exe config $id start= demand | Out-Null   # S12 flips these to auto, on his word
  $acct = (Get-CimInstance Win32_Service -Filter "Name='$id'").StartName
  if ($acct -and ($acct -replace '^\.\\', "$env:COMPUTERNAME\\") -ieq ($cred.UserName -replace '^\.\\', "$env:COMPUTERNAME\\")) {
    Write-Host "  ~ $id installed, runs as $acct, start=demand, NOT running"
  } else {
    Write-Host "  ! $id installed but its logon account reads '$acct', not '$($cred.UserName)'"
    Write-Host "      fix once in services.msc -> $id -> Log On tab, or it will fail to start at S12"
    $failed += "$id (account)"
  }
}

# --- context ---
$id  = "ArsenalFC-Context"
$exe = Join-Path $here "$id.exe"
Copy-Item -LiteralPath $winsw -Destination $exe -Force
# v2 takes NO config argument - it reads "$id.xml" because the exe is named "$id.exe".
& $exe install 2>&1 | ForEach-Object { if ($_ -match "FATAL|Exception") { Write-Host "      winsw: $_" } }
# THE CLAIM IS READ OFF THE OUTCOME, NEVER OFF THE CALL. The previous build printed
# "installed as a SERVICE" unconditionally and said it five times while installing
# NOTHING - the exact defect this whole rung exists to remove, committed inside the
# organ that removes it. Ask the SCM instead.
$svc = Get-Service -Name $id -ErrorAction SilentlyContinue
if (-not $svc) {
  Write-Host "  X $id FAILED to install - see the winsw line(s) above"
  $failed += $id
} else {
  # The account is set through sc.exe, NOT through the XML: WinSW would take a
  # <password> element, and a password persisted in a repo file is the one thing
  # this generator refuses to do.
  sc.exe config $id obj= $cred.UserName password= $plainPw | Out-Null
  sc.exe config $id start= demand | Out-Null   # S12 flips these to auto, on his word
  $acct = (Get-CimInstance Win32_Service -Filter "Name='$id'").StartName
  if ($acct -and ($acct -replace '^\.\\', "$env:COMPUTERNAME\\") -ieq ($cred.UserName -replace '^\.\\', "$env:COMPUTERNAME\\")) {
    Write-Host "  ~ $id installed, runs as $acct, start=demand, NOT running"
  } else {
    Write-Host "  ! $id installed but its logon account reads '$acct', not '$($cred.UserName)'"
    Write-Host "      fix once in services.msc -> $id -> Log On tab, or it will fail to start at S12"
    $failed += "$id (account)"
  }
}

& powershell -ExecutionPolicy Bypass -File (Join-Path $here "ArsenalFC-Turnstile.logon.ps1")
& powershell -ExecutionPolicy Bypass -File (Join-Path $here "ArsenalFC-Dugout.logon.ps1")

Remove-Variable cred, plainPw -ErrorAction SilentlyContinue   # neither outlives this script

Write-Host ""
if ($failed.Count -gt 0) {
  # A non-zero exit, because a summary nobody can act on is how the first version of
  # this script reported five failures as five successes.
  Write-Host "  INCOMPLETE - $($failed.Count) problem(s): $($failed -join ', ')"
  Write-Host "  Nothing is running. Re-run this file after fixing, it is safe to repeat."
  exit 1
}
Write-Host "  DONE - and NOTHING IS RUNNING. Verify:  node scripts/services.mjs status"
Write-Host "  S12 is what turns the organism back on, stage by stage, on your word."
